---
title: "browse_results"
author: "Jovan Tanevski"
date: "`r Sys.Date()`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Setup

Load necessary libraries

```{r setup, message=FALSE}
library(stringr)
library(dplyr)
library(mistyR)
library(future)

plan(multisession)        
```

# Output collection

Find the location of the results for all samples

```{r}
outputs <- str_subset(list.dirs("output"), "processed") %>% 
  str_subset("failed", negate = TRUE)
```

Collect the results for all samples, single modality and all replicates

```{r}
misty.results.codex <- collect_results(str_subset(outputs, "codex"))
misty.results.merfish <- collect_results(str_subset(outputs, "merfish"))
# misty.results.exseq <- collect_results(str_subset(outputs, "exseq"))
```

# Plot basic results

## CODEX

```{r}
  misty.results.codex %>%
    plot_improvement_stats() %>%
    plot_view_contributions() %>%
    plot_interaction_heatmap("intra") %>%
    plot_interaction_heatmap("juxta.15") %>%
    plot_interaction_heatmap("para.100") %>%
    plot_contrast_heatmap("intra", "juxta.15") %>%
    plot_contrast_heatmap("intra", "para.100") %>%
    plot_interaction_communities("intra") %>%
    plot_interaction_communities("juxta.15") %>%
    plot_interaction_communities("para.100")
```

## MERFISH

Filter only genes with mean gain in variance explained of 0.5 or more to plot the gain and view contributions.

```{r}
ts <- misty.results.merfish$improvements.stats %>% 
  filter(measure == "gain.R2", mean > 0.5) %>% pull(target)

temp <- misty.results.merfish

temp$improvements.stats <- misty.results.merfish$improvements.stats %>% filter(target %in% ts)
temp$contributions.stats <- misty.results.merfish$contributions.stats %>% filter(target %in% ts)

temp %>%
  plot_improvement_stats() %>%
  plot_view_contributions()
```

Plot contrasts and communities.

```{r}
misty.results.merfish %>% 
  plot_contrast_heatmap("intra", "juxta.15", 2) %>%  
  plot_contrast_heatmap("intra", "para.100", 1.4)

misty.results.merfish %>% 
  plot_interaction_communities("intra", 2) %>%
  plot_interaction_communities("juxta.15", 2) %>% 
  plot_interaction_communities("para.100", 1.5)
  
```

