---
title: "simple_misty"
author: "Jovan Tanevski"
date: "`r Sys.Date()`"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# Setup

```{r setup, message=FALSE}
library(reticulate)
library(mistyR)
library(future)
library(dplyr)
library(purrr)
library(stringr)

use_python("/usr/local/bin/python3")
plan(multisession)
```


# Extract counts and geometry

Requires `python3` and anndata installed (`pip install anndata`).

```{python}
import anndata

def read_and_extract(datapath):
  adata = anndata.read(datapath)
  counts = adata.obsm["counts"]
  obs = adata.obs
  markers = adata.uns["counts_var"]
  return counts, obs, markers

```

# Run misty 

Define standard view composition and run MISTy on all h5ad files for modalities CODEX, MERFISH and ExSeq.


```{r run_misty}
(list.files("data", ".h5ad", recursive = TRUE, full.names = TRUE) %>%
  keep(~ str_detect(.x, "(codex|merfish)"))) %>%
  walk(function(datapath) {
    data <- py$read_and_extract(datapath)
    
    if (str_detect(datapath, "codex")) {
      transformed <- asinh(as.matrix(data[[1]]))
    } else {
      counts  <- as.matrix(data[[1]])
      transformed <- log((counts/rowSums(counts))*1e5 + 1)
    }
    
    expr <- as.data.frame(transformed)
    colnames(expr) <- make.names(data[[3]])
    obs <- data[[2]]
    pos <- obs %>% select(x_orig, y_orig)

    unique(str_extract(rownames(pos), "-\\d$")) %>% walk(function(replicate) {
      output.folder <- paste0(
        str_replace(
          str_remove(datapath, ".h5ad"),
          "data", "output"
        ), replicate
      )

      output.folder.failed <- paste0(output.folder, "_failed")

      if (!(dir.exists(output.folder) | dir.exists(output.folder.failed))) {
        replicate.ind <- str_which(rownames(pos), paste0(replicate, "$"))

        # in codex filter cells with outlier sizes (Tukey's interquartile approach)
        if (str_detect(datapath, "codex")) {
          sizes <- obs %>%
            slice(replicate.ind) %>%
            pull("size")
          quartiles <- quantile(sizes, c(.25, .75))
          lower <- quartiles[1] - 1.5 * (quartiles[2] - quartiles[1])
          upper <- quartiles[2] + 1.5 * (quartiles[2] - quartiles[1])
          ind <- replicate.ind[which(sizes < upper & sizes > lower)]
        } else {
          ind <- replicate.ind
        }

        misty.views <- create_initial_view(expr[ind, ]) %>%
          add_juxtaview(pos[ind, ]) %>%
          add_paraview(pos[ind, ], l = 100, zoi = 15)

        tryCatch(
          run_misty(misty.views, results.folder = output.folder),
          error = function(e) file.rename(output.folder, output.folder.failed)
        )
      }
    })
  })
```
